name: cicd 

on:
  push:
    branches-ignore:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: 'v1.53.3'
        args: --timeout 3m
    - name: Run build
      run: |
        make docker-build-latest
